export const orders = [
  {
    id: "#ORD-2024-001",
    customer: "John Smith",
    restaurant: "Bella Vista Italian",
    items: ["Margherita Pizza", "Caesar Salad", "Tiramisu"],
    total: 45.99,
    status: "Preparing",
    type: "Dine-in",
    time: "2 mins ago",
    estimatedTime: "15 mins",
    table: "Table 12",
  },
  {
    id: "#ORD-2024-002",
    customer: "Emily Johnson",
    restaurant: "Sakura Sushi Bar",
    items: ["Dragon Roll", "Miso Soup", "Edamame"],
    total: 32.5,
    status: "Ready",
    type: "Pickup",
    time: "5 mins ago",
    estimatedTime: "Ready now",
    table: null,
  },
  {
    id: "#ORD-2024-003",
    customer: "Michael Brown",
    restaurant: "Taco Libre",
    items: ["Beef Tacos (3)", "Guacamole", "Corona Beer"],
    total: 28.75,
    status: "Delivered",
    type: "Delivery",
    time: "12 mins ago",
    estimatedTime: "Delivered",
    table: null,
  },
  {
    id: "#ORD-2024-004",
    customer: "Sarah Davis",
    restaurant: "Le Petit Bistro",
    items: ["Coq au Vin", "French Onion Soup", "Wine"],
    total: 67.8,
    status: "Confirmed",
    type: "Dine-in",
    time: "18 mins ago",
    estimatedTime: "25 mins",
    table: "Table 8",
  },
  {
    id: "#ORD-2024-005",
    customer: "David Wilson",
    restaurant: "Spice Garden",
    items: ["Chicken Tikka Masala", "Naan Bread", "Basmati Rice"],
    total: 24.99,
    status: "Cancelled",
    type: "Delivery",
    time: "25 mins ago",
    estimatedTime: "Cancelled",
    table: null,
  },
  {
    id: "#ORD-2024-006",
    customer: "Lisa Chen",
    restaurant: "Golden Dragon",
    items: ["Sweet & Sour Pork", "Fried Rice", "Spring Rolls"],
    total: 31.25,
    status: "Preparing",
    type: "Pickup",
    time: "8 mins ago",
    estimatedTime: "10 mins",
    table: null,
  },
];