export const staffMembers = [
  {
    id: 1,
    name: "Nabil El Maaroufi",
    email: "nabil@restaurant.com",
    phone: "+212 611223344",
    role: "Head Chef",
    restaurant: "Bella Vista Italian",
    status: "Active",
    shift: "Morning",
    joinDate: "2022-03-15",
    avatar: "/placeholder.svg?height=64&width=64",
    performance: 95,
  },
  {
    id: 2,
    name: "Walid Walid",
    email: "walid@restaurant.com",
    phone: "+212 611223344",
    role: "Manager",
    restaurant: "Sakura Sushi Bar",
    status: "Active",
    shift: "Full Day",
    joinDate: "2021-08-22",
    avatar: "/placeholder.svg?height=64&width=64",
    performance: 98,
  },
  {
    id: 3,
    name: "Samir Samir",
    email: "samir@restaurant.com",
    phone: "+212 611223344",
    role: "Waiter",
    restaurant: "Le Petit Bistro",
    status: "On Break",
    shift: "Evening",
    joinDate: "2023-01-10",
    avatar: "/placeholder.svg?height=64&width=64",
    performance: 87,
  },
  {
    id: 4,
    name: "Imane Imane",
    email: "imane@restaurant.com",
    phone: "+212 611223344",
    role: "Hostess",
    restaurant: "Taco Libre",
    status: "Active",
    shift: "Evening",
    joinDate: "2023-05-03",
    avatar: "/placeholder.svg?height=64&width=64",
    performance: 92,
  },
  {
    id: 5,
    name: "Ahmed Ahmed",
    email: "ahmed@restaurant.com",
    phone: "+212 611223344",
    role: "Sous Chef",
    restaurant: "Golden Dragon",
    status: "Active",
    shift: "Morning",
    joinDate: "2022-11-18",
    avatar: "/placeholder.svg?height=64&width=64",
    performance: 89,
  },
  {
    id: 6,
    name: "Ali Ali",
    email: "ali@restaurant.com",
    phone: "+212 611223344",
    role: "Server",
    restaurant: "Spice Garden",
    status: "Off Duty",
    shift: "Night",
    joinDate: "2023-02-28",
    avatar: "/placeholder.svg?height=64&width=64",
    performance: 94,
  },
];